- name: Setup application environment
  hosts: all
  vars:
    app_name: irisi-app
    jar_file: irisi-0.0.1-SNAPSHOT.jar # Update with the actual JAR file name
    app_user: irisi
    deploy_dir: /opt/irisi
    service_name: irisi-demo
  tasks:
    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
      become: yes
      
    - name: create a user
      ansible.builtin.user:
        name: irisi
        create_home: false
        shell: /bin/false
      become: yes

    - name: create directory for app
      ansible.builtin.file:
        path: /opt/irisi
        state: directory
        owner: irisi
        group: irisi
        mode: 0760
      become: yes
    
    - name: build the app
      ansible.builtin.shell:
        cmd: "./mvnw clean package"
        chdir: "../../app/"
      register: build_output
      delegate_to: localhost

    - name: copy the jar to the app path
      ansible.builtin.copy:
        src: "../../app/target/irisi-0.0.1-SNAPSHOT.jar"
        dest: "~/app.jar"
      delegate_to: localhost

    
    - name: copy the jar to the app path 1
      ansible.builtin.copy:
        src: "~/app.jar"
        dest: "{{ deploy_dir }}/"
        owner: irisi
        group: irisi
        mode: 0760
      become: yes
      
  
    - name: create systemd service
      ansible.builtin.template:
        src: irisi-demo-service.j2
        dest: /etc/systemd/system/irisi-demo.service
      become: yes
    
    - name: reload system daemons
      ansible.builtin.systemd:
        daemon_reload: true 
      become: yes
  
    - name: start and enable application
      ansible.builtin.systemd:
        service: "irisi-demo"
        state: started 
        enabled: true 
      become: yes
